spring.application.name=bookingAPI
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.password=
spring.datasource.username=test
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=22cb37eb41381e9a0752923e2ad2f140f92962c30f2a03f243753786211a2cd6
jwt.expiration=900000